/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bosont;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import net.lingala.zip4j.core.ZipFile;
import net.lingala.zip4j.exception.ZipException;


/**
 *
 * @author Anthe
 */
public class bosonTGUI extends javax.swing.JFrame {
public static String drive;
public static String selectedFileString;
private final static String newline = "\n";
public static String path;
    /**
     * Creates new form bosonTGUI
     */
    
    public bosonTGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBrowseBox = new javax.swing.JTextField();
        jBrowseButton = new javax.swing.JButton();
        bpkButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jText = new javax.swing.JTextArea();
        bpkZipButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBrowseButton.setText("Select APK");
        jBrowseButton.setActionCommand("selectapk");
        jBrowseButton.setName("jBrowseButton"); // NOI18N
        jBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrowseButtonActionPerformed(evt);
            }
        });

        bpkButton.setText("Select files");
        bpkButton.setEnabled(false);
        bpkButton.setName("bpkButton"); // NOI18N
        bpkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpkButtonActionPerformed(evt);
            }
        });

        jText.setEditable(false);
        jText.setColumns(20);
        jText.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jText.setRows(5);
        jText.setEnabled(false);
        jScrollPane1.setViewportView(jText);

        bpkZipButton.setText("Select ZIP");
        bpkZipButton.setActionCommand("SelectZip");
        bpkZipButton.setEnabled(false);
        bpkZipButton.setName("bpkButton"); // NOI18N
        bpkZipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpkZipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBrowseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBrowseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bpkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bpkZipButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBrowseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrowseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bpkZipButton)
                        .addGap(5, 5, 5)
                        .addComponent(bpkButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jBrowseButton.getAccessibleContext().setAccessibleName("butSelectAPK");
        bpkButton.getAccessibleContext().setAccessibleName("okButton");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bosont/title_boson_x_05x.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void unzip(){
    String source = selectedFileString;
    String destination = path + "\temp";
    String password = "password";

    try {
         ZipFile zipFile = new ZipFile(source);
         if (zipFile.isEncrypted()) {
            zipFile.setPassword(password);
         }
         zipFile.extractAll(destination);
    } catch (ZipException e) {
    }
}
    private void jBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrowseButtonActionPerformed
JFileChooser chooser = new JFileChooser();
FileFilter filter = new FileNameExtensionFilter("APK File", new String[] {"apk"});
chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
chooser.setDialogTitle("Select APK");
chooser.setFileSelectionMode(JFileChooser.OPEN_DIALOG);
chooser.setFileFilter(filter);
chooser.addChoosableFileFilter(filter);
//   
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
     
      System.out.println("getSelectedFile() : " 
         +  chooser.getSelectedFile());
      File selectedFile = chooser.getSelectedFile();
      jBrowseBox.setText(selectedFile.getAbsolutePath());
      drive = selectedFile.getAbsolutePath();
      bpkButton.setEnabled(true);
      jText.setEnabled(true);
      bpkZipButton.setEnabled(true);
      }
    
    else {
      System.out.println("No Selection ");
      }                                  
    }//GEN-LAST:event_jBrowseButtonActionPerformed

    private void bpkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpkButtonActionPerformed
 JFileChooser chooser = new JFileChooser();
chooser.setMultiSelectionEnabled(true);
// Retrieve the selected files
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
      File[] files;
    //  Arrays.fill(files,null)
      files = chooser.getSelectedFiles();
for(File file: files)
{
    jText.append(file.getName()+ newline);
}
    }
    
    else {
      System.out.println("No Selection ");
      }                                  
    }//GEN-LAST:event_bpkButtonActionPerformed

    private void bpkZipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpkZipButtonActionPerformed
      JFileChooser chooser = new JFileChooser();
FileFilter filter = new FileNameExtensionFilter("ZIP File", new String[] {"zip"});
chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
chooser.setDialogTitle("Select ZIP");
chooser.setFileSelectionMode(JFileChooser.OPEN_DIALOG);
chooser.setFileFilter(filter);
chooser.addChoosableFileFilter(filter);
//   
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
     
      System.out.println("getSelectedFile() : " 
         +  chooser.getSelectedFile());
      File selectedFile = chooser.getSelectedFile();
      selectedFileString = selectedFile.getAbsolutePath();
    
     
    }
    else {
      System.out.println("No Selection ");
      }                                  
            
    }//GEN-LAST:event_bpkZipButtonActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) throws IOException {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
 try {
        UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) { }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bosonTGUI().setVisible(true);
                
            }
        });
        path = new File(".").getCanonicalPath();
        System.out.println(path);
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bpkButton;
    private javax.swing.JButton bpkZipButton;
    private javax.swing.JTextField jBrowseBox;
    private javax.swing.JButton jBrowseButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jText;
    // End of variables declaration//GEN-END:variables
}
